[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ai_trading_bot = "EkkRQzE2pDWJ1Kfypu9tqaZkKJs9ae8iKugmCHXMKj5a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
